In [1]:
import os
import re
import json
import torch
import pandas as pd
import scanpy as sc
import math
import logging
import importlib
from pathlib import Path
import warnings
import numpy as np
import traceback
import scipy.sparse as sp
import random
from scipy.special import softmax
from concurrent.futures import ProcessPoolExecutor, as_completed
from typing import Tuple, Set, Optional, List, Iterable, Union, Dict, Callable, Any
from anndata import AnnData
import pybedtools
import argparse
import pickle
from sklearn.decomposition import TruncatedSVD

import sys
PROJECT_DIR = "/gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER"
SRC_DIR = str(Path(PROJECT_DIR) / "src")
if SRC_DIR not in sys.path:
    sys.path.insert(0, SRC_DIR)

from multiomic_transformer.utils.peaks import find_genes_near_peaks, format_peaks
import multiomic_transformer.utils.data_formatter as data_formatter

random.seed(1337)
np.random.seed(1337)
torch.manual_seed(1337)

# Training Data Preparation and Caching

The model uses cached per-chromosome data to help speed up training. Here, we will go through the process of building the necessary tensors and reference files to train the gene prediction model.

## Set up the TrainingDataFormatter

The training data formatter ensures that the correct data files and output directories exist and helps to keep everything standardized.

In [2]:
importlib.reload(data_formatter)

In [3]:
# Path to the project directory (same as Git repository root)
project_dir = Path(PROJECT_DIR)

# Path to the training output directory. Used to store the preprocessing config
output_dir = Path("/gpfs/Labs/Uzun/DATA/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/experiments")

# Name of the dataset / experiment to run
dataset_name = "mESC_E7.5_rep1_muon_preprocessing_filter_tfs"

# Organism code for the dataset. Supports either "mm10" or "hg38"
organism_code = "mm10"

# List of samples in the training datset. 
# Each of these should have its own subdirectory in the processed data directory
sample_names = ["E7.5_rep1"]

# List of chromosomes. Used to split the data by chromsome for caching and training.
# Should be in the format "chr1", "chr2", etc. and should match the chromosome names in the processed data files.
chrom_list = [f"chr{i}" for i in range(1, 5)]

tdf = data_formatter.TrainingDataFormatter(
    project_dir=project_dir,
    dataset_name=dataset_name,
    organism_code=organism_code,
    sample_names=sample_names,
    chrom_list=chrom_list,
    output_dir=output_dir / dataset_name,
)

with open(tdf.output_dir / "file_paths.json", "r") as f:
    file_paths = json.load(f)

  - Found existing genome file: /gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/data/genome_data/reference_genome/mm10/mm10.fa.gz
  - mm10.fa.gz is already BGZF; skipping transcode
  - Index already exists: mm10.fa.gz.fai, mm10.fa.gz.gzi
Genome ready: /gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/data/genome_data/reference_genome/mm10/mm10.fa.gz
Found existing gene_info: /gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/data/genome_data/genome_annotation/mm10
Found existing GTF: /gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/data/genome_data/genome_annotation/mm10/Mus_musculus.GRCm39.115.gtf.gz

Map sizes: {'n_official': 143320, 'n_ens2sym': 77920, 'n_entrez2sym': 112254, 'n_alias2sym': 72569}

## Sample-Level Data Preparation

We first load the pseudobulk data from the Muon QC and preprocssing pipeline. The data files are loaded and the peak and gene names are standardized.

We load the pseudobulk data for the sample, which also creates a list of gene names. The `split_genes_into_tfs_and_tgs` function checks which of the genes in the gene name list overlap with an organism-specific [file of TF names from CIS-BP](https://mitra.stanford.edu/kundaje/marinovg/oak/various/motifs/CIS-BP/TF_Information_all_motifs.txt) to create `tfs` and `tgs` attributes.

In [4]:
sample_name = sample_names[0]

pseudobulk_rna_df = tdf.load_pseudobulk_rna_df(sample_name)

print(f"Number of genes: {len(tdf.genes):,}")

# Next the genes are classified as TFs or TGs by checking which genes in the data are in the reference TF list. 
tdf.tfs, tdf.tgs = tdf.split_genes_into_tfs_and_tgs(tdf.genes)
print(f"  - TFs: {len(tdf.tfs):,} (First 3: {tdf.tfs[:3]})")
print(f"  - TGs: {len(tdf.tgs):,} (First 3: {tdf.tgs[:3]})")

Number of genes: 18,862
  - TFs: 1,223 (First 3: ['2010315B03RIK', '2310033P09RIK', '2610008E11RIK'])
  - TGs: 17,627 (First 3: ['0610005C13RIK', '0610009E02RIK', '0610009L18RIK'])

The pseudobulk ATAC data is loaded, which also creates a list of peak names

In [5]:
pseudobulk_atac_df = tdf.load_pseudobulk_atac_df(sample_name)

print(f"Number of peaks: {len(tdf.peaks):,} (First 3: {tdf.peaks[:3]})")

Number of peaks: 199,885 (First 3: ['chr1:3035460-3036350', 'chr1:3044677-3045614', 'chr1:3062482-3063387'])

A BED file of the peak locations is created using `create_peak_bed_file` and the peak locations are stored as a dataframe in `tdf.peak_locs_df`.

In [6]:
tdf.create_peak_bed_file(pseudobulk_atac_df, sample_name)
display(tdf.peak_locs_df.head())

  chrom    start      end strand               peak_id
0  chr1  3035460  3036350      .  chr1:3035460-3036350
1  chr1  3044677  3045614      .  chr1:3044677-3045614
2  chr1  3062482  3063387      .  chr1:3062482-3063387
3  chr1  3072145  3073018      .  chr1:3072145-3073018
4  chr1  3191389  3192286      .  chr1:3191389-3192286

### Calculate peak to gene distance

Next, we will use the peak bed file created when loading the peak pseudobulk dataset to calculate the distance between each peak and each gene within 1 Mb. This will create a bias tensor to help the model prioritize genes that are closer to peaks when training the peak-TG cross-attention portion of the model.

In [7]:
tdf.create_peak_to_tg_distance_file(
    sample_name=sample_name,
    max_peak_distance=1e6,
    distance_factor_scale=25000,
    force_recalculate=False,
    filter_to_nearest_gene=False,
)

Peak to TSS distance file already exists for sample E7.5_rep1 at /gpfs/Labs/Uzun/SCRIPTS/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/data/processed/mESC_E7.5_rep1_muon_preprocessing_filter_tfs/E7.5_rep1/peak_to_gene_dist.parquet. Skipping recalculation.

,peak_chr,peak_start,peak_end,peak_id,gene_chr,gene_start,gene_end,target_id,TSS_dist,TSS_dist_score
0,chr9,55148902,55149745,chr9:55148902-55149745,chr9,55149745,55149746,NRG4,0,1.000000e+00
1,chr7,27251562,27252441,chr7:27251562-27252441,chr7,27252441,27252442,PLD3,0,1.000000e+00
2,chr14,55918361,55919232,chr14:55918361-55919232,chr14,55919232,55919233,TINF2,0,1.000000e+00
3,chr11,57719406,57720297,chr11:57719406-57720297,chr11,57720297,57720298,GM32915,0,1.000000e+00
4,chr8,119436687,119437532,chr8:119436687-119437532,chr8,119437532,119437533,GM63757,0,1.000000e+00
...,...,...,...,...,...,...,...,...,...,...
50488308,chr1,24295262,24296008,chr1:24295262-24296008,chr1,23296008,23296009,GM53541,1000000,4.248354e-18
50488309,chr4,134886177,134887106,chr4:134886177-134887106,chr4,133887106,133887107,GM68734,1000000,4.248354e-18
50488310,chr5,151175820,151176702,chr5:151175820-151176702,chr5,150176702,150176703,GM72600,1000000,4.248354e-18
50488311,chr12,82274207,82275049,chr12:82274207-82275049,chr12,81275049,81275050,GM3693,1000000,4.248354e-18
50488312,chr10,67535774,67536392,chr10:67535774-67536392,chr10,66536392,66536393,GM31181,1000000,4.248354e-18

## Chromosome-Specific Data Formatting

In [8]:
total_TG_pseudobulk_global, pseudobulk_chrom_dict = tdf.aggregate_pseudobulk_datasets(force_recalculate=False)
total_TG_pseudobulk_global.head()

  - Found existing global and per-chrom pseudobulk; loading...

,AAACAGCCAAACTCAT-1,AAACATGCAACCTGGT-1,AAACATGCAATGAATG-1,AAACATGCAATTATGC-1,AAACATGCACCTATAG-1,AAACATGCAGGATAAC-1,AAACCAACATAATCGT-1,AAACCGAAGAGGGACT-1,AAACCGCGTGAACAAA-1,AAACCGCGTTAACGAT-1,...,TTTGTGGCAATAATGG-1,TTTGTGGCACAATGCC-1,TTTGTGGCAGCACCAT-1,TTTGTGGCAGCACGTT-1,TTTGTGGCATGAATAG-1,TTTGTGTTCTGTGAGT-1,TTTGTTGGTACAATGT-1,TTTGTTGGTCCTTCTC-1,TTTGTTGGTTAAGCCA-1,TTTGTTGGTTAATGAC-1
0610005C13RIK,-0.282479,-0.191067,-0.216796,-0.156428,-0.177397,-0.279658,0.432268,-0.227272,-0.187673,-0.250557,...,0.568745,1.896808,-0.263528,-0.264592,-0.269208,-0.222234,-0.130673,-0.277631,1.463841,-0.217445
0610009E02RIK,-0.165841,-0.165913,0.062958,-0.111208,-0.164909,-0.106381,-0.169892,-0.160091,0.923441,-0.157398,...,-0.169728,-0.149924,-0.167922,1.083216,-0.004862,-0.153275,-0.162185,1.451688,-0.107407,-0.015187
0610009L18RIK,-0.051948,0.299400,0.167516,-0.096523,-0.093400,0.071991,-0.039363,-0.081976,-0.025130,-0.056363,...,-0.094679,0.058806,-0.091815,-0.013607,-0.035489,-0.096523,0.154920,-0.094260,-0.096523,-0.028368
0610030E20RIK,-0.261493,-0.235710,0.232739,-0.293941,-0.110585,-0.017197,0.319739,0.087553,-0.078334,0.027293,...,0.339856,0.438889,0.014483,0.186608,-0.043661,-0.250167,0.187243,-0.232593,0.342870,-0.353937
0610038B21RIK,-0.107516,0.158184,-0.072866,-0.101787,-0.104079,-0.072953,-0.036954,0.012016,0.151483,0.255801,...,0.322489,-0.088230,-0.107516,-0.086293,-0.017479,-0.016538,-0.084196,0.731441,0.275296,-0.107516

In [9]:
tdf.create_chrom_files(total_TG_pseudobulk_global, pseudobulk_chrom_dict)

Saved TF tensor with 1223 TFs and 5199 metacells.
  - Number of chromosomes: 4: ['chr1', 'chr2', 'chr3', 'chr4']
  - Processing chromosomes for dataset: mESC_E7.5_rep1_muon_preprocessing_filter_tfs
  - All required output files exist for chr1. Skipping preprocessing.
  - All required output files exist for chr2. Skipping preprocessing.
  - All required output files exist for chr3. Skipping preprocessing.
  - All required output files exist for chr4. Skipping preprocessing.
Preprocessing complete. Wrote per-sample/per-chrom data for MultiomicTransformerDataset.

We can check that all of the required cached files exist for the experiment.

In [10]:
missing_files = tdf.check_cached_file_exist()
print(f"Missing {len(missing_files)} cached files")

All required files are present.

Missing 0 cached files

# Testing how the data prep and caching interacts with the experiment_loader class

In [ ]:
importlib.reload(experiment_loader)

In [12]:
import multiomic_transformer.utils.experiment_loader as experiment_loader
from multiomic_transformer.models.model_simplified import MultiomicTransformer

os.makedirs(
    f"/gpfs/Labs/Uzun/DATA/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/experiments/{dataset_name}/model_training_001",
    exist_ok=True
    )

exp = experiment_loader.ExperimentLoader(
    experiment_dir = "/gpfs/Labs/Uzun/DATA/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/experiments/",
    experiment_name=dataset_name,
    model_num=1,
)

exp.tf_names = tdf.tfs
exp.tg_names = tdf.tgs

preprocesing_setting_dict = {
    "COMMON_DATA" : tdf.file_paths["training_cache"]["common"]["dir"],
    "SAMPLE_DATA_CACHE_DIR": tdf.file_paths["training_cache"]["dataset_dir"],
    "CHROM_IDS": tdf.chrom_list,
}

exp.preprocessing_settings = preprocesing_setting_dict

print("Creating dataset...")
dataset = exp.create_multichrom_dataset(
    max_cached=100,
)

WARNING: Run parameters file /gpfs/Labs/Uzun/DATA/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/experiments/mESC_E7.5_rep1_muon_preprocessing_filter_tfs/model_training_001/run_parameters.json does not exist.
WARNING: Experiment settings file /gpfs/Labs/Uzun/DATA/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/experiments/mESC_E7.5_rep1_muon_preprocessing_filter_tfs/run_parameters_long.csv does not exist.
WARNING: Experiment info file /gpfs/Labs/Uzun/DATA/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/experiments/mESC_E7.5_rep1_muon_preprocessing_filter_tfs/experiment_info.json does not exist.
WARNING: Preprocessing settings file /gpfs/Labs/Uzun/DATA/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/experiments/mESC_E7.5_rep1_muon_preprocessing_filter_tfs/preprocessing_config.json does not exist.
WARNING: GPU usage file not found for mESC_E7.5_rep1_muon_preprocessing_filter_tfs. GPU usage plotting will be unavailable.
WARNING: Training log file /gpfs/Labs/Uzun/DATA/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/experiments/mESC_E7.5_rep1_muon_preprocessing_filter_tfs/model_training_001/training_log.csv does not exist.
WARNING: TF names file /gpfs/Labs/Uzun/DATA/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/experiments/mESC_E7.5_rep1_muon_preprocessing_filter_tfs/model_training_001/tf_names_ordered.json does not exist.
WARNING: TG names file /gpfs/Labs/Uzun/DATA/PROJECTS/2024.SINGLE_CELL_GRN_INFERENCE.MOELLER/experiments/mESC_E7.5_rep1_muon_preprocessing_filter_tfs/model_training_001/tg_names_ordered.json does not exist.

Creating dataset...

In [13]:
batch_size=128

print("Creating dataloaders...")
train_loader, val_loader, test_loader = exp.prepare_dataloader(
    dataset,
    batch_size=batch_size,
    world_size=1,
    rank=0,
    num_workers=8,
    pin_memory=True,
)

print("Creating and fitting scalers...")
scalers = exp.create_scalers(
    dataset=dataset,
    dataloader=train_loader,
    max_batches=100,
)

Creating dataloaders...
Creating and fitting scalers...

In [14]:
from scipy.stats import norm
from sklearn.metrics import roc_auc_score

def format_grn(df):
    def inverse_normal_transform(x):
        r = x.rank(method="average")
        n = len(x)
        p = (r - 0.5) / n          # avoids 0 and 1
        return norm.ppf(p)
    
    # Apply rank-based inverse normal transform (INT)
    df["Score"] = df.groupby("Source")["Score"].transform(inverse_normal_transform)
    
    df = df.dropna()
    
    df["Source"] = df["Source"].astype(str).str.upper()
    df["Target"] = df["Target"].astype(str).str.upper()
    
    return df

def quick_pooled_auroc(exp, labeled_df):
    balanced = exp._balance_pos_neg(labeled_df, random_state=42)
    y = balanced["_in_gt"].astype(int).to_numpy()
    s = balanced["Score"].to_numpy()
    
    auroc = roc_auc_score(y, s)
    
    return auroc

def quick_per_tf_auroc(exp, labeled_df):
    per_tf_auroc = []
    
    for tf, group in labeled_df.groupby("Source"):
        balanced = exp._balance_pos_neg(group, random_state=42)
        y = balanced["_in_gt"].astype(int).to_numpy()
        s = balanced["Score"].to_numpy()
        
        if len(np.unique(y)) > 1:
            auroc = roc_auc_score(y, s)
            per_tf_auroc.append(auroc)
        else:
            per_tf_auroc.append(np.nan)  # or some default value for TFs with only pos or neg examples
    
    median_per_tf_auroc = np.nanmedian(per_tf_auroc)
    
    return median_per_tf_auroc

In [15]:
first_batch = next(iter(train_loader))
atac_wins, tf_tensor, tg_tensor, bias, tf_ids, tg_ids, motif_mask = first_batch
print("Shapes of first batch:")
print(f"atac_wins: {atac_wins.shape}")
print(f"tf_tensor: {tf_tensor.shape}")
print(f"tg_tensor: {tg_tensor.shape}")
print(f"bias: {bias.shape if bias is not None else None}")
print(f"tf_ids: {tf_ids.shape}")
print(f"tg_ids: {tg_ids.shape}")

Shapes of first batch:
atac_wins: torch.Size([128, 13849, 1])
tf_tensor: torch.Size([128, 1223])
tg_tensor: torch.Size([128, 914])
bias: torch.Size([914, 13849])
tf_ids: torch.Size([1223])
tg_ids: torch.Size([914])

In [16]:
import time

epochs = 5
bias_scale = 0.0
num_layers = 1
num_heads = 1
d_model = 64
d_ff = d_model*4
window_pool_size = 128

max_training_batches = 25
max_grad_attrib_batches = 10

training_time_size_dict = {}

GROUND_TRUTH_DIR = Path(PROJECT_DIR) / "data" / "ground_truth_files"
ground_truth = exp.load_ground_truth(GROUND_TRUTH_DIR / "chipatlas_macrophage.csv")

print(f"\n=== Running experiment with window_pool_size={window_pool_size} ===")

# ----- Create a new model -----
model = exp.create_new_model(
dataset=dataset,
    bias_scale=bias_scale,
    d_model=d_model,
    num_heads=num_heads,
    num_layers=num_layers,
    d_ff=d_ff,
    dropout=0.1,
    window_pool_size=window_pool_size,
)

# ----- Train the model and log GPU memory and batch times -----
train_time_start = time.time()
model = exp.train_timed(
    model,
    train_loader,
    val_loader,
    num_epochs=epochs,
    validate_every=1,
    max_batches=max_training_batches,
    monitor_gpu_memory=True,
    profile_batches=True,
)
train_time_end = time.time()

# ----- Gradient Attribution on the Trained Model -----
selected_experiment_dir = exp.model_training_dir / "grn_results_by_checkpoint" / "testing_bias_scale"
start_time = time.time()
grad_attr_df, grad_batch_dfs = exp.run_gradient_attribution(
    selected_experiment_dir=exp.model_training_dir,
    model=model,
    test_loader=test_loader,
    tf_scaler=scalers["tf_scaler"],
    tg_scaler=scalers["tg_scaler"],
    tf_names = exp.tf_names,
    tg_names = exp.tg_names,
    use_amp=False,
    max_batches=max_grad_attrib_batches,
    device=exp.device,
    save_every_n_batches=1,
    max_tgs_per_batch=128,
)

end_time = time.time()
print(f"  - Gradient attribution finished {max_grad_attrib_batches} batches in {end_time - start_time:.2f} seconds.")

# ----- Calculate the AUROC -----
ground_truth_df, gt_lookup = ground_truth

df = format_grn(grad_attr_df)[["Source", "Target", "Score"]].copy()

labeled_df = exp.create_ground_truth_comparison_df(df, gt_lookup, "ChIP-Atlas macrophage")

y_all = labeled_df["_in_gt"].fillna(0).astype(int).to_numpy()
s_all = labeled_df["Score"].to_numpy()

# Calculate the pooled AUROC and per-TF median AUROC
pooled_auroc = quick_pooled_auroc(exp, labeled_df)
per_tf_median_auroc = quick_per_tf_auroc(exp, labeled_df)
auroc_df = pd.DataFrame({
    "window_pool_size": window_pool_size,
    "pooled_auroc": pooled_auroc,
    "per_tf_median_auroc": per_tf_median_auroc,
}, index=[0])

# Calculate the training time and average time per epoch
training_time = train_time_end - train_time_start
avg_time_per_epoch = training_time / epochs
training_time_size_dict[window_pool_size] = {
    "total": training_time,
    "avg_per_epoch": avg_time_per_epoch
}

exp.gpu_mem_log_df["window_pool_size"] = window_pool_size
exp.batch_profile_df["window_pool_size"] = window_pool_size

=== Running experiment with window_pool_size=128 ===

Epoch 1/5:  12%|██████▎                                              | 3/25 [00:00<00:03,  5.95it/s]

loader_s      0.106229
transfer_s    0.002545
forward_s     0.279353
backward_s    0.111022
optim_s       0.000000
dtype: float64
loader_s      0.053283
transfer_s    0.002051
forward_s     0.144630
backward_s    0.064911
optim_s       0.000000
dtype: float64
loader_s      0.035598
transfer_s    0.002474
forward_s     0.100572
backward_s    0.060270
optim_s       0.000000
dtype: float64
loader_s      0.026777
transfer_s    0.002427
forward_s     0.077669
backward_s    0.048454
optim_s       0.005876
dtype: float64
loader_s      0.021457
transfer_s    0.002423
forward_s     0.063618
backward_s    0.041353
optim_s       0.004701
dtype: float64
loader_s      0.017906
transfer_s    0.002279
forward_s     0.054148
backward_s    0.036411
optim_s       0.003918
dtype: float64

Epoch 1/5:  44%|██████████████████████▉                             | 11/25 [00:00<00:00, 19.55it/s]

loader_s      0.015427
transfer_s    0.002426
forward_s     0.047556
backward_s    0.033278
optim_s       0.003358
dtype: float64
loader_s      0.013539
transfer_s    0.002410
forward_s     0.042682
backward_s    0.030769
optim_s       0.003131
dtype: float64
loader_s      0.012072
transfer_s    0.002410
forward_s     0.038761
backward_s    0.028791
optim_s       0.002783
dtype: float64
loader_s      0.010886
transfer_s    0.002324
forward_s     0.035560
backward_s    0.027093
optim_s       0.002505
dtype: float64
loader_s      0.009915
transfer_s    0.002413
forward_s     0.033049
backward_s    0.025940
optim_s       0.002277
dtype: float64
loader_s      0.009107
transfer_s    0.002404
forward_s     0.030910
backward_s    0.024863
optim_s       0.002213
dtype: float64
loader_s      0.008419
transfer_s    0.002404
forward_s     0.029191
backward_s    0.023966
optim_s       0.002042
dtype: float64
loader_s      0.007832
transfer_s    0.002344
forward_s     0.027589
backward_s    0.023091
optim_s       0.001897
dtype: float64

Epoch 1/5:  76%|███████████████████████████████████████▌            | 19/25 [00:01<00:00, 28.44it/s]

loader_s      0.007323
transfer_s    0.002408
forward_s     0.026283
backward_s    0.022513
optim_s       0.001770
dtype: float64
loader_s      0.006886
transfer_s    0.002400
forward_s     0.025103
backward_s    0.021919
optim_s       0.001762
dtype: float64
loader_s      0.006494
transfer_s    0.002401
forward_s     0.024068
backward_s    0.021391
optim_s       0.001658
dtype: float64
loader_s      0.006146
transfer_s    0.002354
forward_s     0.023111
backward_s    0.020857
optim_s       0.001566
dtype: float64
loader_s      0.005834
transfer_s    0.002404
forward_s     0.022318
backward_s    0.020520
optim_s       0.001484
dtype: float64
loader_s      0.005560
transfer_s    0.002399
forward_s     0.021576
backward_s    0.020145
optim_s       0.001486
dtype: float64
loader_s      0.005305
transfer_s    0.002399
forward_s     0.020904
backward_s    0.019804
optim_s       0.001415
dtype: float64
loader_s      0.005074
transfer_s    0.002361
forward_s     0.020266
backward_s    0.019436
optim_s       0.001351
dtype: float64

loader_s      0.004863
transfer_s    0.002402
forward_s     0.019734
backward_s    0.019218
optim_s       0.001292
dtype: float64
loader_s      0.004669
transfer_s    0.002397
forward_s     0.019221
backward_s    0.018961
optim_s       0.001306
dtype: float64
loader_s      0.004490
transfer_s    0.002397
forward_s     0.018750
backward_s    0.018719
optim_s       0.001254
dtype: float64

Epoch 1/5 | Train Loss: 0.1543 | Val MSE: 0.1301 | R2 (Unscaled): -0.557 | R2 (Scaled): -0.557 | LR: 1.00e-04 | Time: 1.2s

Epoch 2/5:   4%|██                                                   | 1/25 [00:00<00:02,  8.35it/s]

loader_s      0.007840
transfer_s    0.002398
forward_s     0.018322
backward_s    0.018517
optim_s       0.001205
dtype: float64
loader_s      0.007564
transfer_s    0.002369
forward_s     0.017901
backward_s    0.018269
optim_s       0.001161
dtype: float64
loader_s      0.007301
transfer_s    0.002403
forward_s     0.017551
backward_s    0.018135
optim_s       0.001119
dtype: float64

Epoch 2/5:  20%|██████████▌                                          | 5/25 [00:00<00:00, 24.88it/s]

loader_s      0.007066
transfer_s    0.002400
forward_s     0.017215
backward_s    0.017957
optim_s       0.001151
dtype: float64
loader_s      0.006838
transfer_s    0.002400
forward_s     0.016889
backward_s    0.017791
optim_s       0.001113
dtype: float64
loader_s      0.006633
transfer_s    0.002373
forward_s     0.016564
backward_s    0.017596
optim_s       0.001077
dtype: float64
loader_s      0.006433
transfer_s    0.002402
forward_s     0.016302
backward_s    0.017503
optim_s       0.001043
dtype: float64
loader_s      0.006245
transfer_s    0.002399
forward_s     0.016042
backward_s    0.017368
optim_s       0.001059
dtype: float64

Epoch 2/5:  36%|███████████████████                                  | 9/25 [00:00<00:00, 30.84it/s]

loader_s      0.006067
transfer_s    0.002399
forward_s     0.015792
backward_s    0.017238
optim_s       0.001028
dtype: float64
loader_s      0.005908
transfer_s    0.002375
forward_s     0.015537
backward_s    0.017082
optim_s       0.000998
dtype: float64
loader_s      0.005749
transfer_s    0.002401
forward_s     0.015330
backward_s    0.017010
optim_s       0.000971
dtype: float64

Epoch 2/5:  52%|███████████████████████████                         | 13/25 [00:00<00:00, 33.68it/s]

loader_s      0.005603
transfer_s    0.002398
forward_s     0.015115
backward_s    0.016902
optim_s       0.000988
dtype: float64
loader_s      0.005461
transfer_s    0.002398
forward_s     0.014912
backward_s    0.016797
optim_s       0.000962
dtype: float64
loader_s      0.005328
transfer_s    0.002377
forward_s     0.014705
backward_s    0.016668
optim_s       0.000937
dtype: float64
loader_s      0.005201
transfer_s    0.002400
forward_s     0.014536
backward_s    0.016612
optim_s       0.000914
dtype: float64
loader_s      0.005079
transfer_s    0.002397
forward_s     0.014361
backward_s    0.016530
optim_s       0.000930
dtype: float64

Epoch 2/5:  68%|███████████████████████████████████▎                | 17/25 [00:00<00:00, 35.53it/s]

loader_s      0.004963
transfer_s    0.002398
forward_s     0.014195
backward_s    0.016444
optim_s       0.000907
dtype: float64
loader_s      0.004852
transfer_s    0.002378
forward_s     0.014024
backward_s    0.016335
optim_s       0.000886
dtype: float64
loader_s      0.004747
transfer_s    0.002399
forward_s     0.013886
backward_s    0.016292
optim_s       0.000866
dtype: float64

Epoch 2/5:  84%|███████████████████████████████████████████▋        | 21/25 [00:00<00:00, 36.63it/s]

loader_s      0.004655
transfer_s    0.002397
forward_s     0.013742
backward_s    0.016218
optim_s       0.000882
dtype: float64
loader_s      0.004559
transfer_s    0.002397
forward_s     0.013604
backward_s    0.016146
optim_s       0.000863
dtype: float64
loader_s      0.004469
transfer_s    0.002379
forward_s     0.013458
backward_s    0.016052
optim_s       0.000844
dtype: float64
loader_s      0.004380
transfer_s    0.002398
forward_s     0.013344
backward_s    0.016019
optim_s       0.000827
dtype: float64
loader_s      0.004298
transfer_s    0.002397
forward_s     0.013259
backward_s    0.015959
optim_s       0.000880
dtype: float64

loader_s      0.004216
transfer_s    0.002397
forward_s     0.013141
backward_s    0.015900
optim_s       0.000862
dtype: float64

Epoch 2/5 | Train Loss: 0.1326 | Val MSE: 0.1138 | R2 (Unscaled): -0.368 | R2 (Scaled): -0.368 | LR: 1.00e-04 | Time: 0.8s

Epoch 3/5:   8%|████▏                                                | 2/25 [00:00<00:01, 16.87it/s]

loader_s      0.005512
transfer_s    0.002398
forward_s     0.013033
backward_s    0.015844
optim_s       0.000845
dtype: float64
loader_s      0.005410
transfer_s    0.002382
forward_s     0.012915
backward_s    0.015765
optim_s       0.000829
dtype: float64
loader_s      0.005318
transfer_s    0.002399
forward_s     0.012823
backward_s    0.015744
optim_s       0.000813
dtype: float64
loader_s      0.005239
transfer_s    0.002397
forward_s     0.012722
backward_s    0.015698
optim_s       0.000827
dtype: float64

Epoch 3/5:  24%|████████████▋                                        | 6/25 [00:00<00:00, 28.66it/s]

loader_s      0.005147
transfer_s    0.002397
forward_s     0.012626
backward_s    0.015652
optim_s       0.000812
dtype: float64
loader_s      0.005060
transfer_s    0.002382
forward_s     0.012521
backward_s    0.015584
optim_s       0.000798
dtype: float64
loader_s      0.004977
transfer_s    0.002398
forward_s     0.012443
backward_s    0.015566
optim_s       0.000784
dtype: float64
loader_s      0.004895
transfer_s    0.002396
forward_s     0.012354
backward_s    0.015523
optim_s       0.000798
dtype: float64

Epoch 3/5:  40%|████████████████████▊                               | 10/25 [00:00<00:00, 33.10it/s]

loader_s      0.004815
transfer_s    0.002396
forward_s     0.012270
backward_s    0.015480
optim_s       0.000784
dtype: float64
loader_s      0.004738
transfer_s    0.002382
forward_s     0.012178
backward_s    0.015418
optim_s       0.000771
dtype: float64
loader_s      0.004665
transfer_s    0.002397
forward_s     0.012110
backward_s    0.015406
optim_s       0.000759
dtype: float64
loader_s      0.004593
transfer_s    0.002396
forward_s     0.012033
backward_s    0.015370
optim_s       0.000771
dtype: float64

Epoch 3/5:  56%|█████████████████████████████                       | 14/25 [00:00<00:00, 35.07it/s]

loader_s      0.004523
transfer_s    0.002396
forward_s     0.011977
backward_s    0.015336
optim_s       0.000759
dtype: float64
loader_s      0.004456
transfer_s    0.002383
forward_s     0.011895
backward_s    0.015280
optim_s       0.000747
dtype: float64
loader_s      0.004393
transfer_s    0.002397
forward_s     0.011861
backward_s    0.015267
optim_s       0.000736
dtype: float64
loader_s      0.004331
transfer_s    0.002396
forward_s     0.011802
backward_s    0.015234
optim_s       0.000775
dtype: float64

Epoch 3/5:  72%|█████████████████████████████████████▍              | 18/25 [00:00<00:00, 35.30it/s]

loader_s      0.004269
transfer_s    0.002396
forward_s     0.011742
backward_s    0.015204
optim_s       0.000764
dtype: float64
loader_s      0.004210
transfer_s    0.002384
forward_s     0.011669
backward_s    0.015153
optim_s       0.000752
dtype: float64
loader_s      0.004154
transfer_s    0.002397
forward_s     0.011615
backward_s    0.015143
optim_s       0.000742
dtype: float64
loader_s      0.004098
transfer_s    0.002396
forward_s     0.011555
backward_s    0.015112
optim_s       0.000754
dtype: float64

Epoch 3/5:  88%|█████████████████████████████████████████████▊      | 22/25 [00:00<00:00, 36.22it/s]

loader_s      0.004043
transfer_s    0.002396
forward_s     0.011519
backward_s    0.015085
optim_s       0.000743
dtype: float64
loader_s      0.003990
transfer_s    0.002384
forward_s     0.011454
backward_s    0.015039
optim_s       0.000733
dtype: float64
loader_s      0.003941
transfer_s    0.002397
forward_s     0.011406
backward_s    0.015031
optim_s       0.000723
dtype: float64
loader_s      0.003890
transfer_s    0.002395
forward_s     0.011352
backward_s    0.015005
optim_s       0.000734
dtype: float64

loader_s      0.003841
transfer_s    0.002395
forward_s     0.011299
backward_s    0.014978
optim_s       0.000725
dtype: float64
Epoch 3/5 | Train Loss: 0.1191 | Val MSE: 0.1062 | R2 (Unscaled): -0.272 | R2 (Scaled): -0.272 | LR: 1.00e-04 | Time: 0.7s

Epoch 4/5:   4%|██                                                   | 1/25 [00:00<00:02,  8.13it/s]

loader_s      0.004997
transfer_s    0.002396
forward_s     0.011291
backward_s    0.014958
optim_s       0.000715
dtype: float64
loader_s      0.005411
transfer_s    0.002386
forward_s     0.011278
backward_s    0.014921
optim_s       0.000706
dtype: float64

Epoch 4/5:  16%|████████▍                                            | 4/25 [00:00<00:01, 17.20it/s]

loader_s      0.005345
transfer_s    0.002398
forward_s     0.011274
backward_s    0.014919
optim_s       0.000697
dtype: float64
loader_s      0.005281
transfer_s    0.002397
forward_s     0.011251
backward_s    0.014900
optim_s       0.000726
dtype: float64
loader_s      0.005219
transfer_s    0.002397
forward_s     0.011204
backward_s    0.014879
optim_s       0.000717
dtype: float64
loader_s      0.005158
transfer_s    0.002386
forward_s     0.011155
backward_s    0.014841
optim_s       0.000708
dtype: float64

Epoch 4/5:  32%|████████████████▉                                    | 8/25 [00:00<00:00, 25.80it/s]

loader_s      0.005097
transfer_s    0.002398
forward_s     0.011121
backward_s    0.014838
optim_s       0.000699
dtype: float64
loader_s      0.005038
transfer_s    0.002396
forward_s     0.011075
backward_s    0.014816
optim_s       0.000710
dtype: float64
loader_s      0.004985
transfer_s    0.002397
forward_s     0.011032
backward_s    0.014795
optim_s       0.000701
dtype: float64
loader_s      0.004929
transfer_s    0.002387
forward_s     0.010982
backward_s    0.014759
optim_s       0.000693
dtype: float64

Epoch 4/5:  48%|████████████████████████▉                           | 12/25 [00:00<00:00, 30.41it/s]

loader_s      0.004875
transfer_s    0.002397
forward_s     0.010948
backward_s    0.014756
optim_s       0.000685
dtype: float64
loader_s      0.004821
transfer_s    0.002396
forward_s     0.010907
backward_s    0.014735
optim_s       0.000696
dtype: float64
loader_s      0.004770
transfer_s    0.002396
forward_s     0.010867
backward_s    0.014716
optim_s       0.000688
dtype: float64
loader_s      0.004719
transfer_s    0.002387
forward_s     0.010821
backward_s    0.014683
optim_s       0.000680
dtype: float64

Epoch 4/5:  64%|█████████████████████████████████▎                  | 16/25 [00:00<00:00, 33.03it/s]

loader_s      0.004668
transfer_s    0.002397
forward_s     0.010789
backward_s    0.014680
optim_s       0.000672
dtype: float64
loader_s      0.004620
transfer_s    0.002396
forward_s     0.010767
backward_s    0.014665
optim_s       0.000683
dtype: float64
loader_s      0.004575
transfer_s    0.002396
forward_s     0.010731
backward_s    0.014646
optim_s       0.000675
dtype: float64
loader_s      0.004528
transfer_s    0.002387
forward_s     0.010688
backward_s    0.014615
optim_s       0.000668
dtype: float64

Epoch 4/5:  80%|█████████████████████████████████████████▌          | 20/25 [00:00<00:00, 34.76it/s]

loader_s      0.004483
transfer_s    0.002397
forward_s     0.010659
backward_s    0.014613
optim_s       0.000661
dtype: float64
loader_s      0.004438
transfer_s    0.002396
forward_s     0.010630
backward_s    0.014597
optim_s       0.000671
dtype: float64
loader_s      0.004395
transfer_s    0.002396
forward_s     0.010596
backward_s    0.014581
optim_s       0.000664
dtype: float64
loader_s      0.004352
transfer_s    0.002387
forward_s     0.010557
backward_s    0.014552
optim_s       0.000657
dtype: float64

loader_s      0.004310
transfer_s    0.002396
forward_s     0.010531
backward_s    0.014551
optim_s       0.000650
dtype: float64
loader_s      0.004269
transfer_s    0.002395
forward_s     0.010512
backward_s    0.014538
optim_s       0.000660
dtype: float64
loader_s      0.004232
transfer_s    0.002396
forward_s     0.010482
backward_s    0.014521
optim_s       0.000653
dtype: float64

Epoch 4/5 | Train Loss: 0.1115 | Val MSE: 0.1003 | R2 (Unscaled): -0.203 | R2 (Scaled): -0.203 | LR: 1.00e-04 | Time: 0.8s

Epoch 5/5:   8%|████▏                                                | 2/25 [00:00<00:01, 17.96it/s]

loader_s      0.004804
transfer_s    0.002396
forward_s     0.010454
backward_s    0.014511
optim_s       0.000647
dtype: float64
loader_s      0.004759
transfer_s    0.002388
forward_s     0.010422
backward_s    0.014485
optim_s       0.000640
dtype: float64
loader_s      0.005000
transfer_s    0.002397
forward_s     0.010400
backward_s    0.014485
optim_s       0.000634
dtype: float64

Epoch 5/5:  20%|██████████▌                                          | 5/25 [00:00<00:00, 23.19it/s]

loader_s      0.004954
transfer_s    0.002396
forward_s     0.010378
backward_s    0.014470
optim_s       0.000644
dtype: float64
loader_s      0.004908
transfer_s    0.002396
forward_s     0.010350
backward_s    0.014456
optim_s       0.000638
dtype: float64
loader_s      0.004865
transfer_s    0.002388
forward_s     0.010316
backward_s    0.014431
optim_s       0.000632
dtype: float64
loader_s      0.004821
transfer_s    0.002397
forward_s     0.010309
backward_s    0.014434
optim_s       0.000626
dtype: float64

Epoch 5/5:  36%|███████████████████                                  | 9/25 [00:00<00:00, 29.75it/s]

loader_s      0.004778
transfer_s    0.002396
forward_s     0.010282
backward_s    0.014421
optim_s       0.000635
dtype: float64
loader_s      0.004737
transfer_s    0.002396
forward_s     0.010255
backward_s    0.014407
optim_s       0.000629
dtype: float64
loader_s      0.004696
transfer_s    0.002388
forward_s     0.010224
backward_s    0.014384
optim_s       0.000623
dtype: float64
loader_s      0.004656
transfer_s    0.002396
forward_s     0.010204
backward_s    0.014385
optim_s       0.000617
dtype: float64

Epoch 5/5:  52%|███████████████████████████                         | 13/25 [00:00<00:00, 32.83it/s]

loader_s      0.004617
transfer_s    0.002395
forward_s     0.010180
backward_s    0.014372
optim_s       0.000626
dtype: float64
loader_s      0.004577
transfer_s    0.002395
forward_s     0.010169
backward_s    0.014362
optim_s       0.000621
dtype: float64
loader_s      0.004540
transfer_s    0.002388
forward_s     0.010141
backward_s    0.014340
optim_s       0.000615
dtype: float64
loader_s      0.004503
transfer_s    0.002396
forward_s     0.010132
backward_s    0.014344
optim_s       0.000610
dtype: float64

Epoch 5/5:  68%|███████████████████████████████████▎                | 17/25 [00:00<00:00, 34.55it/s]

loader_s      0.004466
transfer_s    0.002395
forward_s     0.010108
backward_s    0.014332
optim_s       0.000619
dtype: float64
loader_s      0.004429
transfer_s    0.002395
forward_s     0.010085
backward_s    0.014320
optim_s       0.000614
dtype: float64
loader_s      0.004395
transfer_s    0.002388
forward_s     0.010057
backward_s    0.014299
optim_s       0.000609
dtype: float64
loader_s      0.004360
transfer_s    0.002396
forward_s     0.010040
backward_s    0.014301
optim_s       0.000604
dtype: float64

Epoch 5/5:  84%|███████████████████████████████████████████▋        | 21/25 [00:00<00:00, 35.88it/s]

loader_s      0.004326
transfer_s    0.002395
forward_s     0.010017
backward_s    0.014290
optim_s       0.000612
dtype: float64
loader_s      0.004292
transfer_s    0.002395
forward_s     0.009996
backward_s    0.014279
optim_s       0.000607
dtype: float64
loader_s      0.004260
transfer_s    0.002388
forward_s     0.009970
backward_s    0.014258
optim_s       0.000602
dtype: float64
loader_s      0.004227
transfer_s    0.002396
forward_s     0.009963
backward_s    0.014262
optim_s       0.000597
dtype: float64

loader_s      0.004195
transfer_s    0.002395
forward_s     0.009942
backward_s    0.014252
optim_s       0.000606
dtype: float64
loader_s      0.004164
transfer_s    0.002395
forward_s     0.009921
backward_s    0.014242
optim_s       0.000601
dtype: float64

Epoch 5/5 | Train Loss: 0.1059 | Val MSE: 0.0969 | R2 (Unscaled): -0.161 | R2 (Scaled): -0.161 | LR: 1.00e-04 | Time: 0.8s

Gradient attributions: 100%|███████████████████████████████████| 10/10 [00:11<00:00,  1.13s/batches]

  - Gradient attribution finished 10 batches in 11.64 seconds.